#!/bin/bash

# Copyright (C) 2026 Applied Intuition
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Meant to be run in an isolated test container.
#
# Install stol, set up an xfs filesystem, and let the user test it

set -euo pipefail

LOOP=$(losetup -f)
mknod "$LOOP" b 7 "${LOOP##/dev/loop}" 2>/dev/null || true
truncate -s 2G /xfs.img
losetup "$LOOP" /xfs.img
mkfs.xfs -q -m reflink=1 "$LOOP"
mkdir -p /mnt/work
mount "$LOOP" /mnt/work

# Make a copy and install from there
cp -r /pkg /build
make -C /build install PREFIX=/usr/local

export STOL_ROOT=/mnt/work
export STOL_PREFIX=test

echo 'source /usr/local/share/stol/stol.bash' >>/root/.bashrc
exec bash
