#!/bin/bash

# Copyright (C) 2026 Applied Intuition
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -euo pipefail

BRANCH="main"
NAME=""

show-help() {
  echo >&2 "stol init [--branch <branch>] <name>"
}

while [[ ${#} -gt 0 ]]
do
  opt="${1}"
  shift

  case "${opt}" in
    -h | --help)
      show-help
      exit 0
      ;;
    --branch)
      BRANCH="$1"
      shift
      ;;
    *)
      if [[ -n "$NAME" ]]
      then
        echo >&2 "Unexpected argument: ${opt}"
        show-help
        exit 1
      fi
      NAME="${opt}"
      ;;
  esac
done

if [[ -z "$NAME" ]]
then
  echo >&2 "Must provide a name"
  show-help
  exit 1
fi

DST_PROJ_PATH="$STOL_ROOT/projects/$NAME"
REPO_PATH="$DST_PROJ_PATH/.repo"

if [[ -d "$DST_PROJ_PATH" ]]
then
  echo >&2 "Project $NAME already exists at $DST_PROJ_PATH"
  exit 1
fi

set -x

mkdir -p "$DST_PROJ_PATH"
git init -b "$BRANCH" "$REPO_PATH"
git -C "$REPO_PATH" commit --allow-empty -m "init"
git -C "$REPO_PATH" switch --detach HEAD
# branch 'rel/1.0' becomes dir '00-rel--1.0'
git -C "$REPO_PATH" worktree add "$DST_PROJ_PATH/00-${BRANCH//\//--}" "$BRANCH"

set +x
echo "stol dir: $DST_PROJ_PATH"
